//! Build script: embeds the Salt standard library into the saltc binary.
//!
//! Walks `std/` at compile time, collects all .salt files, and generates
//! `src/stdlib_bundle.rs` containing a static map from import path to source.
//! This lets saltc resolve `std.core.ptr` without needing `std/` on disk.

use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=std/");
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let std_dir = Path::new(&manifest_dir).join("std");
    if !std_dir.is_dir() {
        println!("cargo:warning=std/ directory not found — stdlib will not be bundled");
        return;
    }

    let mut entries: Vec<(String, String)> = Vec::new();
    walk_salt_files(&std_dir, &manifest_dir, "", &mut entries);

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("stdlib_bundle.rs");

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs. Do not edit.\n");
    code.push_str("use std::collections::HashMap;\n\n");
    code.push_str("pub(crate) fn stdlib_sources() -> HashMap<String, &'static str> {\n");
    code.push_str("    let mut m = HashMap::new();\n");

    for (import_path, abs_path) in &entries {
        code.push_str(&format!(
            "    m.insert(\"{}\".to_string(), include_str!(\"{}\"));\n",
            import_path, abs_path
        ));
    }

    code.push_str("    m\n");
    code.push_str("}\n");

    fs::write(dest, code).expect("failed to write stdlib_bundle.rs");
}

fn walk_salt_files(dir: &Path, manifest_dir: &str, prefix: &str, entries: &mut Vec<(String, String)>) {
    let entries_fs = match fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };
    for entry in entries_fs.flatten() {
        let path = entry.path();
        let name = path.file_name().unwrap().to_str().unwrap();
        if name.starts_with('.') {
            continue;
        }
        if path.is_dir() {
            let new_prefix = if prefix.is_empty() {
                name.to_string()
            } else {
                format!("{}.{}", prefix, name)
            };
            walk_salt_files(&path, manifest_dir, &new_prefix, entries);
        } else if name.ends_with(".salt") {
            // Compute import path: std.core.ptr
            let import_path = path.to_str().unwrap()
                .trim_start_matches(manifest_dir)
                .trim_start_matches('/')
                .trim_end_matches(".salt")
                .replace(['/', '\\'], ".");
            // Absolute path for include_str!
            let abs = path.to_str().unwrap().to_string();
            entries.push((import_path, abs));
        }
    }
}
